name: Tests
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/stokewhere/flour-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install flour
        run: |
          . /deps/venv/bin/activate
          maturin develop
      - name: Lint with flake8
        run: |
          . /deps/venv/bin/activate
          flake8 .
  mypy:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/stokewhere/flour-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install flour
        run: |
          . /deps/venv/bin/activate
          maturin develop
      - name: Run mypy
        run: |
          . /deps/venv/bin/activate
          mypy .
  isort:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/stokewhere/flour-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install flour
        run: |
          . /deps/venv/bin/activate
          maturin develop
      - name: Run isort
        run: |
          . /deps/venv/bin/activate
          isort --check .
  black:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/stokewhere/flour-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install flour
        run: |
          . /deps/venv/bin/activate
          maturin develop
      - name: Run black
        run: |
          . /deps/venv/bin/activate
          black --check .
  pytest:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/stokewhere/flour-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install flour
        run: |
          . /deps/venv/bin/activate
          maturin develop
      - name: Run pytest
        run: |
          . /deps/venv/bin/activate
          pytest

  cargo-check:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/stokewhere/flour-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Cargo check
        run: cargo check

  cargo-fmt:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/stokewhere/flour-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Cargo fmt
        run: cargo fmt --check

  cargo-clippy:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/stokewhere/flour-testing-environment:latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Cargo clippy
        run: cargo clippy -- -D warnings
